### ISSUE TITLE
Idea for people without supporting libraries for pdftools

### ISSUE THREAD

**Issue by elinw** [trinker/textreadr#15]
I'm importing textreadr but I don't want installation of my package to fail because users don't have libpoppler-cpp and a significant portion of my intended users won't have shell access or know what to do with it.    So actually, that means I'm currently only suggesting textreadr, but that just postpones the issue to when they use a function that uses textreadr.   So I'm going to make using textreadr conditional on whether pdftools is installed.       
This will work but then my users not only can't read pdfs, they also can't read doc, docx etc.    I was wondering if you would be interested in a PR that would allow users to use textreadr only for non PDFs.

**Comment by trinker** [comment]
@elinw Any renewed interest in this?

**Comment by trinker** [comment]
Closing because the user never submitted the PR.  Feel free to reopen.
