### ISSUE TITLE
read_document assumes online pdf link is http, and doesn't use read_pdf

### ISSUE THREAD

**Issue by bbrewington** [trinker/textreadr#18]
Here's the function call I tried (and subsequent error):
```r
read_document("http://www.dailyscript.com/scripts/12+and+Holding.pdf")
```

`Error in sub(re, "", x, perl = TRUE) : input string 1 is invalid UTF-8`

Here's the chunk of code I think is incorrect:
https://github.com/trinker/textreadr/blob/f1cea8c2887e064f195ce2522c5788568616fed3/R/read_document.R#L64-L69

**Comment by trinker** [comment]
Thanks for the spot.  Much appreciated!
