### ISSUE TITLE
unzip and xml errors 

### ISSUE THREAD

**Issue by ngathan** [trinker/textreadr#21]
Hi, 

Thanks for the great package. I have been using it, but recently encountered the following issue when reading a docx file. 

My code: 

tempt <- read_docx("~/FakeArticles/Another Random Article.docx")

Error: 

Error: '/var/folders/qp/skqpgk3s40xgtf8z1whd066c0000gn/T//RtmpKLT4DN/file869ca748bd9/word/document.xml' does not exist.
In addition: Warning message:
In utils::unzip(file, exdir = tmp) : error 1 in extracting from zip file

I appreciate your help. 

Best, 

Nga Than

**Comment by trinker** [comment]
Do you have the file you can supply?  And can you try supplying the full path to the file without the ~

**Comment by trinker** [comment]
Closing as the user never provided the error file.  Feel free to re-open.
