### ISSUE TITLE
check_antiword_installed doesn't find antiword

### ISSUE THREAD

**Issue by jjesusfilho** [trinker/textreadr#5]
I manually downloaded antiword, but the command check_antiword_installed  doesn't find it. I am using linux. If I type in command line "which antiword" I get the following response: usr/bin/antiword. But textreadr can't find it.

**Comment by trinker** [comment]
What does this give you:

```
check_antiword_installed('usr/bin/antiword/antiword.exe')
```

**Comment by jjesusfilho** [comment]
check_antiword_installed('usr/bin/antiword/antiword.exe')
checking if antiword is installed...
antiword does not appear to be installed in root.
Would you like me to try to install it there?
1: Yes
2: No
Selection: 1Let me try...
Hold on.  It may take some time...
Error in check_antiword_installed("usr/bin/antiword/antiword.exe") :
  Currently only Windows installs are handled.
Please consider installing yourself...
http://www.winfield.demon.nl


José de Jesus Filho, PhD
Analista de dados jurídicos
(11) 2372-9811 (11) 98522-0210
http://www.josejesus.info

2017-04-17 16:11 GMT-03:00 Tyler Rinker <notifications@github.com>:

**Comment by trinker** [comment]
There are some Windows based checks.  I will utilize Unix approaches conditionally.  Can you try the following:
```
Sys.which("antiword")
```

**Comment by jjesusfilho** [comment]
Sys.which("antiword")           antiword
"/usr/bin/antiword"


José de Jesus Filho, PhD
Analista de dados jurídicos
(11) 2372-9811 (11) 98522-0210
http://www.josejesus.info

2017-04-17 23:31 GMT-03:00 Tyler Rinker <notifications@github.com>:

**Comment by trinker** [comment]
Thank you for that.  Can you tell me if this gives the proper location:

```
antiword_loc <- function(){

    myPaths <- c("antiword", "~/.cabal/bin/antiword", "~/Library/Haskell/bin/antiword",
        "C:\\PROGRA~1\\antiword\\antiword.exe", "/usr/bin/antiword",
        "/Applications/antiword.app/Contents/MacOS/antiword", 
        file.path(strsplit(getwd(), "(/|\\\\)+")[[1]][1], 'antiword/antiword.exe'))
    
    panloc <- Sys.which(myPaths)
    temp <- panloc[panloc != ""]

    short.path <- which.min(unlist(lapply(gregexpr("[Aa]ntiword", temp), "[[", 1)))
    temp[short.path]
}

antiword_loc()
```

**Comment by jjesusfilho** [comment]
Yes:

antiword_loc()           antiword
"/usr/bin/antiword"


José de Jesus Filho, PhD
Analista de dados jurídicos
(11) 2372-9811 (11) 98522-0210
http://www.josejesus.info

2017-04-18 10:04 GMT-03:00 Tyler Rinker <notifications@github.com>:

**Comment by trinker** [comment]
Thank you I edited the response on GitHub.  Can you take a look and answer
the othe rpotion:
https://github.com/trinker/textreadr/issues/5#issuecomment-294834229

Thank you for your help.

**Comment by jjesusfilho** [comment]
I installed it using sudo apt-get install antiword

José de Jesus Filho, PhD
Analista de dados jurídicos
(11) 2372-9811 (11) 98522-0210
http://www.josejesus.info

2017-04-18 11:50 GMT-03:00 Tyler Rinker <notifications@github.com>:

> Thank you I edited the response on GitHub. Can you take a look and answer
> the othe rpotion:
> https://github.com/trinker/textreadr/issues/5#issuecomment-294834229
>
> Thank you for your help.
>
>
> On Tue, Apr 18, 2017 at 10:24 AM, José de Jesus Filho <

**Comment by trinker** [comment]
One more part can you run:

```
file.exists(antiword_loc())
```

**Comment by jjesusfilho** [comment]
`file.exists(antiword_loc())`
[1] TRUE

**Comment by trinker** [comment]
@jjesusfilho can you try reinstalling the dev version 

```
library(devtools)
install_github('trinker/textreadr')
```

...and try the following:

```
check_antiword_installed()
check_antiword_installed('usr/bin/antiword')

x <- system.file("docs/Yasmine_Interview_Transcript.doc", package = "textreadr")
read_doc(x)
```

Hopefully, we can close this if all checks out.

**Comment by jjesusfilho** [comment]
When I run:
`check_antiword_installed()`

I get:
checking if antiword is installed...

antiword appears to be installed.

...Let the .doc extraction begin!

But when I run:

`check_antiword_installed('usr/bin/antiword')
`
I get:

checking if antiword is installed...

Error in install_anitword_linux() : 
  Antiword must be installed first.  Please install first:

sudo apt-get install antiword

Anyway, It's working now and I was able to read all my doc texts.

Thank you very much. By the way, I love your packages and I have promoted them in the Brazilian R community.

Cheers.

**Comment by trinker** [comment]
Thank you very much.  Your support and word of mouth advertisement are greatly appreciated.

Can you try one last thing.  I think I know the original problem with the path.  Try:

```
check_antiword_installed('/usr/bin/antiword')
```

I believe it needs a leading slash on Linux.  I have added your contribution to the NEWS file as well: https://github.com/trinker/textreadr/blob/master/NEWS

**Comment by trinker** [comment]
I got Linux up and running and confirm it was the leading slash.  I'm closing this.
